// Bundles the MCP server (and its CI smoketest harness) into single
// self-contained CommonJS files under mcp-server/dist/.
//
// The output is `.cjs` so the surrounding `type:module` package can't
// reinterpret it as ESM, and it runs with a plain `node dist/server.cjs`
// from any directory — no `--experimental-strip-types`, no Node 22.6
// requirement, no dependency on the source-tree layout. This is the exact
// artifact the Claude Code plugin ships and designers run.

import * as esbuild from "esbuild";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const outdir = join(here, "dist");

// The same single source the UI's `__APP_VERSION__` and the assembled plugin's
// manifest take theirs from, so the two halves of the Bridge cannot disagree
// about what "the current build" means (#189). Stamped at build time because
// the bundle runs from anywhere and cannot find this file at runtime; a server
// built without this step reports `source` and declines to compare.
const version = JSON.parse(
  readFileSync(join(here, "..", "package.json"), "utf8"),
).version;

const shared = {
  bundle: true,
  platform: "node",
  target: "node18",
  format: "cjs",
  define: { __SERVER_VERSION__: JSON.stringify(version) },
  // `ws` lazily requires these native acceleration addons and guards their
  // absence; leaving them external keeps the bundle pure-JS and portable.
  external: ["bufferutil", "utf-8-validate"],
  logLevel: "info",
};

await Promise.all([
  esbuild.build({
    ...shared,
    entryPoints: [join(here, "src/server.ts")],
    outfile: join(outdir, "server.cjs"),
    banner: {
      js: "// Tidy DS Toolbox — bundled MCP server (generated by build.js; do not edit)",
    },
  }),
  // The smoketest is bundled too so CI can run it with plain `node` on the
  // CI Node version (no experimental TS-stripping flag, which is 22.6+ only).
  esbuild.build({
    ...shared,
    entryPoints: [join(here, "src/smoketest.ts")],
    outfile: join(outdir, "smoketest.cjs"),
  }),
]);
